// Re-export shared types for frontend use
export type {
  AgentRole,
  SenderType,
  MeetingPhase,
  MeetingMode,
  ParticipantStatus,
  ArtifactType,
  QuickActionType,
  Message,
  Artifact,
  Participant,
  Room,
  Decision,
  ActionItem,
  AgentTypingEvent,
  PhaseChangedEvent,
  TurnState,
  BufferedMessage,
  AgentTurn,
  AgentAudioDeltaEvent,
  AgentTranscriptDeltaEvent,
  AgentVisemeDeltaEvent,
  AgentResponseDoneEvent,
  // Meeting Interaction types
  Mention,
  VisualHint,
  StructuredAgentOutput,
  VisualType,
  SecretaryRole,
  AllAgentRole,
  ArtifactFileType,
  // Meeting Interaction events
  AgentThinkingEvent,
  HumanCalloutEvent,
  BigScreenRenderData,
  BigScreenUpdateEvent,
  MonitorContent,
  MonitorUpdateEvent,
  SophiaMessageEvent,
  ArtifactsReadyEvent,
  MeetingBroadcastEvent,
  BrandMemorySet,
  PricingTier,
  CompetitorInfo,
  ExternalLink,
} from "../../../shared/types.ts";
