// Centralized UI strings — English (en)
// Ref: CLAUDE.md §Language & i18n Policy
// All UI strings MUST be referenced from this file, never hardcoded.

export const S = {
  app: {
    name: "BizRoom",
    tagline: "Your AI Executive Team",
  },
  meeting: {
    start: "Let's start the meeting.",
    end: "Meeting adjourned.",
    phase: {
      idle: "Idle",
      opening: "Opening",
      briefing: "Briefing",
      discussion: "Discussion",
      decision: "Decision",
      action: "Action Plan",
      closing: "Closing",
    },
  },
  agents: {
    coo: { name: "Hudson", role: "COO", title: "Chief Operating Officer" },
    cfo: { name: "Amelia", role: "CFO", title: "Chief Financial Officer" },
    cmo: { name: "Yusef", role: "CMO", title: "Chief Marketing Officer" },
    cto: { name: "Kelvin", role: "CTO", title: "Chief Technology Officer" },
    cdo: { name: "Jonas", role: "CDO", title: "Chief Design Officer" },
    clo: { name: "Bradley", role: "CLO", title: "Chief Legal Officer" },
    sophia: { name: "Sophia", role: "AI Secretary", title: "AI Secretary" },
  },
  input: {
    placeholder: "Enter your agenda...",
    placeholderAuto: "Enter discussion topic...",
    placeholderDm: (name: string) => `Message ${name}...`,
    send: "Send",
    startAuto: "Start Discussion",
    stopAuto: "Stop Discussion",
    pttHint: "Hold Space to speak",
    recording: "Recording...",
    processing: "Processing...",
  },
  mode: {
    live: "Live",
    auto: "Auto",
    dm: "DM",
    selectDmAgent: "Select an executive to chat with",
    autoObserving: "AI executives are in autonomous discussion",
    autoPrompt: "Enter a topic and AI will discuss autonomously",
  },
  quickActions: {
    agree: "Agree",
    disagree: "Disagree",
    next: "Next",
    hold: "Hold",
  },
  typing: {
    single: (name: string) => `${name} is typing...`,
    multiple: (names: string[]) => `${names.join(", ")} are typing...`,
  },
  sidebar: {
    channels: "Channels",
    participants: "Participants",
    agents: "AI Executives",
    humans: "Members",
  },
  artifacts: {
    download: "Download",
    preview: "Preview",
    minutes: "Meeting Minutes",
    excel: "Excel Report",
  },
  drawer: {
    title: "Resources",
    visualizations: "Visualizations",
    searchResults: "Research Results",
    meetingArtifacts: "Meeting Artifacts",
    preview: "View",
    download: "Download",
    empty: "No artifacts generated yet",
    close: "Close",
  },
  camera: {
    firstPersonHint: "First Person · V to switch",
    overviewHint: "Overview · V to switch",
    backMonitorHint: "Monitor · ` to return",
  },
  monitor: {
    briefingReady: "Briefing Ready",
  },
  brandMemory: {
    stepTitle: "Company Setup",
    stepSubtitle: "AI executives will understand your company and join the meeting",
    presetButton: "Apply Demo Preset",
    presetApplied: "Maestiq preset applied",
    required: "Required",
    companyName: "Company Name",
    industry: "Industry",
    productName: "Product / Service",
    foundedDate: "Founded",
    founderName: "Founder",
    teamSize: "Team Size",
    mission: "Mission",
    vision: "Vision",
    productDescription: "One-line Description",
    targetCustomer: "Target Customer",
    techStack: "Tech Stack",
    revenueModel: "Revenue Model",
    marketSize: "Market Size",
    currentStage: "Current Stage",
    funding: "Funding",
    goals: "Goals",
    brandCopy: "Brand Copy",
    positioning: "Positioning",
    sectionBasic: "Basic Info",
    sectionProduct: "Product / Service",
    sectionMarket: "Market & Competition",
    sectionFinance: "Finance & Goals",
    sectionBrand: "Brand Copy",
    next: "Next",
    back: "Back",
    skip: "Skip",
  },
  agenda: {
    stepTitle: "Meeting Agenda",
    stepSubtitle: "Enter the topics you'd like to discuss today",
    placeholder: "e.g. BizRoom.ai go-to-market strategy",
  },
  lobby: {
    title: "BizRoom",
    subtitle: "AI C-Suite Virtual Office",
    nameLabel: "Enter your name",
    namePlaceholder: "e.g. Alex",
    createRoom: "Create Room",
    joinRoom: "Join Room",
    joinRoomTab: "Join",
    createRoomTab: "Create",
    roomIdPlaceholder: "Room code (e.g. BZ-A3F9)",
    shareLink: "Copy Invite Link",
    linkCopied: "Copied!",
    roomCode: "Room Code",
    waitingMembers: "Waiting for team members...",
    roomFull: "Room is full (max 3 members)",
    you: "(you)",
    enterRoom: "Enter Room",
    createHint: "Create a room and invite your team",
    joinHint: "Enter the room code to join",
    backToLobby: "← Back to Lobby",
    leaveConfirm: "Leave the meeting?\nAll conversation history will be lost.",
    leaveYes: "Leave",
    leaveCancel: "Cancel",
    waitingForHost: "Waiting for host...",
    roomNotFound: "Room not found",
  },
  overlay: {
    participantsHeading: "Executives Present",
    speaking: "Speaking",
    thinking: "Thinking...",
  },
  ceo: {
    requestAiOpinion: "Request AI Opinion",
    nextAgenda: "Next Agenda",
    pauseAi: "Pause AI",
    resumeAi: "Resume AI",
    endMeeting: "End Meeting",
    endMeetingConfirm:
      "End the meeting?\nMeeting minutes and artifacts will be generated.",
  },
  mic: {
    on: "Mic On",
    off: "Mic Off",
    connecting: "Connecting mic...",
  },
  errors: {
    connectionFailed: "Failed to connect to server",
    sendFailed: "Failed to send message",
    micPermission: "Microphone access is required",
    boundary: {
      title: "Something went wrong",
      unknown: "An unknown error occurred",
      reload: "Reload",
    },
  },
} as const;
