// Centralized UI strings — Korean (ko)
// Ref: CLAUDE.md §Language & i18n Policy
// All UI strings MUST be referenced from this file, never hardcoded.

export const S = {
  app: {
    name: "BizRoom",
    tagline: "Your AI Executive Team",
  },
  meeting: {
    start: "회의를 시작하겠습니다",
    end: "회의를 종료합니다",
    phase: {
      idle: "대기 중",
      opening: "개회",
      briefing: "브리핑",
      discussion: "토론",
      decision: "의사결정",
      action: "실행계획",
      closing: "폐회",
    },
  },
  agents: {
    coo: { name: "Hudson", role: "COO", title: "최고운영책임자" },
    cfo: { name: "Amelia", role: "CFO", title: "최고재무책임자" },
    cmo: { name: "Yusef", role: "CMO", title: "최고마케팅책임자" },
    cto: { name: "Kelvin", role: "CTO", title: "최고기술책임자" },
    cdo: { name: "Jonas", role: "CDO", title: "최고디자인책임자" },
    clo: { name: "Bradley", role: "CLO", title: "최고법무책임자" },
  },
  input: {
    placeholder: "안건을 입력하세요...",
    placeholderAuto: "토론 주제를 입력하세요...",
    placeholderDm: (name: string) => `${name}에게 메시지를 보내세요...`,
    send: "전송",
    startAuto: "토론 시작",
    stopAuto: "토론 중지",
    pttHint: "Space를 길게 누르면 음성 입력",
    recording: "녹음 중...",
  },
  mode: {
    live: "Live",
    auto: "Auto",
    dm: "DM",
    selectDmAgent: "대화할 임원을 선택하세요",
    autoObserving: "AI 임원진이 자율 토론 중입니다",
    autoPrompt: "토론 주제를 입력하면 AI가 자율적으로 토론합니다",
  },
  quickActions: {
    agree: "동의",
    disagree: "반대",
    next: "다음",
    hold: "보류",
  },
  typing: {
    single: (name: string) => `${name}이(가) 입력 중...`,
    multiple: (names: string[]) => `${names.join(", ")}이(가) 입력 중...`,
  },
  sidebar: {
    channels: "채널",
    participants: "참여자",
    agents: "AI 임원진",
    humans: "참여자",
  },
  artifacts: {
    download: "다운로드",
    preview: "미리보기",
    minutes: "회의록",
    excel: "Excel 보고서",
  },
  camera: {
    firstPersonHint: "1인칭 · V 전환",
    overviewHint: "전체 시점 · V 전환",
    backMonitorHint: "모니터 · ` 복귀",
  },
  monitor: {
    briefingReady: "Briefing Ready",
  },
  lobby: {
    title: "BizRoom",
    subtitle: "AI C-Suite Virtual Office",
    nameLabel: "이름을 입력하세요",
    namePlaceholder: "예: 김대표",
    createRoom: "회의실 만들기",
    joinRoom: "회의실 참가",
    joinRoomTab: "참가하기",
    createRoomTab: "만들기",
    roomIdPlaceholder: "회의실 코드 (예: BZ-A3F9)",
    shareLink: "초대 링크 복사",
    linkCopied: "복사되었습니다!",
    roomCode: "회의실 코드",
    waitingMembers: "팀원 초대 대기 중",
    roomFull: "회의실이 가득 찼습니다 (최대 3명)",
    you: "(나)",
    enterRoom: "입장하기",
    createHint: "회의실을 만들고 팀원을 초대하세요",
    joinHint: "회의실 코드를 입력하고 참가하세요",
    backToLobby: "← 로비로 돌아가기",
    waitingForHost: "호스트를 기다리는 중...",
    roomNotFound: "존재하지 않는 회의실입니다",
  },
  overlay: {
    participantsHeading: "참여 임원",
    speaking: "발언 중",
    thinking: "생각 중...",
  },
  chairman: {
    requestAiOpinion: "AI 의견 요청",
    nextAgenda: "다음 안건",
    pauseAi: "AI 일시정지",
    resumeAi: "AI 재개",
  },
  mic: {
    on: "마이크 켜짐",
    off: "마이크 꺼짐",
    connecting: "마이크 연결 중...",
  },
  errors: {
    connectionFailed: "서버 연결에 실패했습니다",
    sendFailed: "메시지 전송에 실패했습니다",
    micPermission: "마이크 접근 권한이 필요합니다",
    boundary: {
      title: "문제가 발생했습니다",
      unknown: "알 수 없는 오류가 발생했습니다",
      reload: "새로고침",
    },
  },
} as const;
